# Bin size for BAF data in kb format
bin_size_baf: 10kb
# Bin size for RDR data in kb format
bin_size_rdr: 100kb
# List of chromosomes to consider.
# Ensure chr prefix added if necessary
chromosomes:
  - chr1
  - chr2
  - chrX
# Whether to parallelise by chromosome
chromosome_parallel: True
# Minimum base quality
min_bqual: 30
# Minimum mapping quality
min_mqual: 30

# Boyle lab black list
# https://github.com/Boyle-Lab/Blacklist/blob/master/lists/hg38-blacklist.v2.bed.gz
black_list_file: /home/andrew/projects/share/ref/GRCh38/hg38-blacklist.v2.bed.gz
# BigWig format mappability file
# https://zenodo.org/records/5521424/files/hg38.fa.mappability_150bp.bw
map_file: /foo/bar/ref/GRCh38/hg38.fa.mappability_150bp.bw
# Path to FASTA file for reference genome (should have .fai index file)
ref_genome_file: /foo/bar/ref/GRCh38/Homo_sapiens_assembly38.fasta

# Path to normal BAM file
normal_bam_file: /foo/bar/data/normal.bam
# Dictionary of tumour BAM files
# Keys are sample IDs and values paths to BAM files
tumour_bam_files:
  A: /foo/bar/data/A.bam
  B: /foo/bar/data/B.bam
# Path to file with SNPs from normal samples in either BCF or VCF format
snp_file: /foo/bar/data/snps.bcf

# Pipeline working directory
pipeline_dir: /foo/bar/analysis/wgs_cnv_pp/pipeline
# Pipeline output directory
out_dir: /foo/bar/analysis/wgs_cnv_pp/output